[package]
name = "key-mcursor"
version = "1.0.0"
edition = "2024"

[dependencies]
x11rb = { version = "0.14", features = ["randr", "shape"] }
tiny-skia = "0.12"
fontdue = "0.9"
anyhow = "1"
libc = "0.2"
clap = { version = "4", features = ["derive"] }
const_format = "0.2"
nix = { version = "0.31", features = ["fs", "ioctl", "mman", "poll", "user"] }
bytemuck = { version = "1", features = ["derive"] }
log = "0.4"
env_logger = "0.11"
bitflags = "2"
wayland-client = "0.31"
wayland-protocols-wlr = { version = "0.3", features = ["client"] }
wayland-backend = { version = "0.3", features = ["client_system"] }

[profile.dev]
opt-level = 1

[profile.dev.package.tiny-skia]
opt-level = 2

[profile.dev.package.fontdue]
opt-level = 2

[profile.release]
opt-level = 3
lto = true
# codegen-units = 1
panic = "abort"
